language: python
install: skip

sudo: required

branches:
  only:
    - master
    - /^release-.*/

services:
  - docker
env:
  global:
    - REGISTRY_USER=compss
    - secure: ""
    - TEST_CASSANDRA_VERSION=3.11.4

before_script:
    - source launch_cassandra.sh
    - docker build --tag bscwdc/dislib .
    - docker run $(bash <(curl -s https://codecov.io/env)) --network cassandra_bridge -d --name dislib bscwdc/dislib


script: "docker exec -e CONTACT_NAMES=$CONTACT_NAMES dislib /dislib/run_ci_checks.sh"

after_script:
  - docker images
  - docker exec dislib /dislib/bin/print_tests_logs.sh

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag bscwdc/dislib bscwdc/dislib:latest
deploy:
  provider: script
  script: docker push bscwdc/dislib:latest
  on:
    branch: master


